name: phospholipid-llm-mining
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pyyaml[version='>=6.0']
  - pip
  - requests[version='>=2.31']
  - pandas[version='>=2.2']
  - python-dotenv[version='>=1.0']
  - snakemake-minimal[version='>=8']
  - pytest[version='>=8']
